# Generated by Django 4.2.27 on 2026-08-11 06:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_participacion_fecha_aportacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('autorizacion_dgoj', models.CharField(blank=True, help_text='Resolución de la Dirección General de Ordenación del Juego. Sin ella no se puede abrir la venta.', max_length=120, verbose_name='Nº de autorización DGOJ')),
            ],
            options={
                'verbose_name': 'organizador',
                'verbose_name_plural': 'organizadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('premio_descripcion', models.CharField(max_length=255)),
                ('precio_participacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_participaciones', models.PositiveIntegerField(help_text='Nº total de participaciones emitidas. La tasa del 20 % se anticipa sobre este número, no sobre las vendidas.', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_por_pedido', models.PositiveIntegerField(default=50)),
                ('reserva_minutos', models.PositiveIntegerField(default=10)),
                ('fecha_inicio_venta', models.DateField()),
                ('fecha_sorteo', models.DateField(help_text='No puede distar más de un año del inicio de la venta.')),
                ('caducidad_premio_meses', models.PositiveIntegerField(default=12, help_text='Plazo para reclamar el premio. La normativa exige un mínimo de doce meses.', validators=[django.core.validators.MinValueValidator(12)])),
                ('territorio', models.CharField(default='Todo el territorio español', max_length=200)),
                ('version_bases', models.CharField(default='1.0', max_length=20)),
                ('notaria_nombre', models.CharField(blank=True, max_length=200)),
                ('notaria_poblacion', models.CharField(blank=True, max_length=120)),
                ('inmueble_direccion', models.CharField(blank=True, max_length=255)),
                ('inmueble_superficie', models.CharField(blank=True, max_length=80)),
                ('inmueble_referencia_catastral', models.CharField(blank=True, max_length=40)),
                ('inmueble_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('inmueble_cargas', models.TextField(default='Libre de cargas y gravámenes.')),
                ('inmueble_gastos', models.TextField(default='Los gastos de notaría, registro e impuestos derivados de la transmisión corren por cuenta del ganador.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_venta', 'En venta'), ('cerrado', 'Venta cerrada'), ('sorteado', 'Sorteado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorteos', to='sorteo.organizador')),
                ('proyecto', models.OneToOneField(help_text='Proyecto del ERP que soporta la economía de este sorteo.', on_delete=django.db.models.deletion.PROTECT, related_name='sorteo', to='core.proyecto')),
            ],
            options={
                'verbose_name': 'sorteo',
                'verbose_name_plural': 'sorteos',
                'ordering': ['-fecha_sorteo'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(db_index=True, max_length=12, verbose_name='localizador')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('caducado', 'Caducado')], default='pendiente', max_length=20)),
                ('version_bases', models.CharField(max_length=20)),
                ('acepta_bases_en', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255)),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='sorteo.sorteo')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Papeleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('reservada', 'Reservada'), ('pagada', 'Pagada')], default='libre', max_length=20)),
                ('reserva_expira', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papeletas', to='sorteo.pedido')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeletas', to='sorteo.sorteo')),
            ],
            options={
                'verbose_name': 'papeleta',
                'verbose_name_plural': 'papeletas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ActaSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_premiado', models.PositiveIntegerField()),
                ('protocolo', models.CharField(max_length=120, verbose_name='nº de protocolo')),
                ('notario', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateField()),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sorteo.pedido')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sorteo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='acta', to='sorteo.sorteo')),
            ],
            options={
                'verbose_name': 'acta de sorteo',
                'verbose_name_plural': 'actas de sorteo',
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['sorteo', 'estado'], name='sorteo_pedi_sorteo__0495bd_idx'),
        ),
        migrations.AddIndex(
            model_name='papeleta',
            index=models.Index(fields=['sorteo', 'estado'], name='sorteo_pape_sorteo__3ca79e_idx'),
        ),
        migrations.AddIndex(
            model_name='papeleta',
            index=models.Index(fields=['estado', 'reserva_expira'], name='sorteo_pape_estado_faca92_idx'),
        ),
        migrations.AddConstraint(
            model_name='papeleta',
            constraint=models.UniqueConstraint(fields=('sorteo', 'numero'), name='papeleta_unica_por_sorteo'),
        ),
    ]
