# Generated by Django 4.2.27 on 2026-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizador',
            name='datos_registrales',
            field=models.CharField(blank=True, help_text='Registro Mercantil, tomo, folio y hoja. Figura en las bases.', max_length=255),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='dias_reintegro',
            field=models.PositiveIntegerField(default=30, help_text='Plazo de reintegro si el sorteo se cancela.'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='fecha_fin_venta',
            field=models.DateField(blank=True, help_text='Último día de venta de participaciones.', null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='hora_sorteo',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='importe_ingreso_cuenta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo si se repercute a la persona premiada.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='inmueble_datos_registrales',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='minimo_participaciones',
            field=models.PositiveIntegerField(blank=True, help_text='Mínimo de participaciones vendidas para celebrar el sorteo. Si se deja vacío, el sorteo se celebra incondicionalmente.', null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='organizador_asume_ingreso_cuenta',
            field=models.BooleanField(default=True, verbose_name='El organizador asume el ingreso a cuenta del IRPF'),
        ),
    ]
