# Generated by Django 4.2.27 on 2026-08-11 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sorteo', '0002_organizador_datos_registrales_sorteo_dias_reintegro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio_pago',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen',
            field=models.CharField(choices=[('web', 'Web'), ('manual', 'Registro manual')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Solo en registros manuales.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
