# Generated by Django 4.2.27 on 2026-08-11 07:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_pedido_medio_pago_pedido_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='comision_pago_porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.30'), help_text='Depende del tamaño medio del pedido. Con Stripe y pedidos de 3 participaciones ronda el 2,3 %.', max_digits=5, verbose_name='Comisión media de la pasarela (%)'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='tasa_juego_porcentaje',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Tasa sobre actividades de juego (%)'),
        ),
    ]
