# Generated by Django 4.2.27 on 2026-08-11 07:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0004_sorteo_comision_pago_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('provincia', models.CharField(blank=True, help_text='Una plaza de garaje interesa sobre todo cerca. Saber de dónde viene la demanda cambia dónde se hace la campaña.', max_length=60)),
                ('participaciones_estimadas', models.PositiveIntegerField(default=1)),
                ('precio_maximo', models.CharField(choices=[('10', 'Hasta 10 €'), ('20', 'Hasta 20 €'), ('25', 'Hasta 25 €'), ('50', 'Hasta 50 €'), ('51', 'Más de 50 €')], default='10', max_length=4)),
                ('mayor_edad', models.BooleanField(default=False)),
                ('acepta_aviso', models.BooleanField(default=False, verbose_name='Consiente recibir el aviso de apertura')),
                ('token_baja', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('baja_en', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sorteo', models.ForeignKey(blank=True, help_text='Puede no existir todavía cuando alguien se apunta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interesados', to='sorteo.sorteo')),
            ],
            options={
                'verbose_name': 'interesado',
                'verbose_name_plural': 'interesados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='interesado',
            constraint=models.UniqueConstraint(fields=('sorteo', 'email'), name='interesado_unico_por_sorteo'),
        ),
    ]
