# Generated by Django 4.2.27 on 2026-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0005_interesado_interesado_interesado_unico_por_sorteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='hash_listado',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='participaciones_vendidas_cierre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
