# Generated by Django 4.2.30 on 2026-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0006_sorteo_cerrado_en_sorteo_hash_listado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='comunidad',
            field=models.CharField(blank=True, choices=[('andalucia', 'Andalucía'), ('aragon', 'Aragón'), ('asturias', 'Asturias'), ('baleares', 'Baleares'), ('canarias', 'Canarias'), ('cantabria', 'Cantabria'), ('castilla_la_mancha', 'Castilla-La Mancha'), ('castilla_leon', 'Castilla y León'), ('cataluna', 'Cataluña'), ('valencia', 'Comunitat Valenciana'), ('extremadura', 'Extremadura'), ('galicia', 'Galicia'), ('madrid', 'Madrid'), ('murcia', 'Murcia'), ('navarra', 'Navarra'), ('pais_vasco', 'País Vasco'), ('rioja', 'La Rioja'), ('ceuta', 'Ceuta'), ('melilla', 'Melilla')], max_length=30, verbose_name='Comunidad autónoma del inmueble'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='operacion_compra',
            field=models.CharField(blank=True, choices=[('itp', 'ITP · compra a particular o segunda transmisión'), ('iva', 'IVA + AJD · primera entrega de promotor')], default='itp', max_length=10, verbose_name='Impuesto de la compra'),
        ),
    ]
