# Generated by Django 4.2.30 on 2026-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0007_sorteo_comunidad_sorteo_operacion_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorteo',
            name='compra_para_reventa',
            field=models.BooleanField(default=True, help_text='Condición de los tipos reducidos por reventa profesional.', verbose_name='Se adquiere para revender, dentro de la actividad inmobiliaria'),
        ),
        migrations.AddField(
            model_name='sorteo',
            name='supuesto_reducido',
            field=models.CharField(blank=True, help_text='Déjalo vacío para calcular al tipo general. Los supuestos que podrían aplicar se listan en el panel del sorteo.', max_length=40, verbose_name='Tipo reducido aplicado'),
        ),
    ]
