# Generated by Django 4.2.30 on 2026-08-11 09:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0045_alter_documentoproyecto_options_and_more'),
        ('sorteo', '0008_sorteo_compra_para_reventa_sorteo_supuesto_reducido'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('notas', models.TextField(blank=True)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de referencia de Catastro. Si es mayor que el precio, es la base del impuesto.', max_digits=12, null=True)),
                ('comunidad', models.CharField(blank=True, choices=[('andalucia', 'Andalucía'), ('aragon', 'Aragón'), ('asturias', 'Asturias'), ('baleares', 'Baleares'), ('canarias', 'Canarias'), ('cantabria', 'Cantabria'), ('castilla_la_mancha', 'Castilla-La Mancha'), ('castilla_leon', 'Castilla y León'), ('cataluna', 'Cataluña'), ('valencia', 'Comunitat Valenciana'), ('extremadura', 'Extremadura'), ('galicia', 'Galicia'), ('madrid', 'Madrid'), ('murcia', 'Murcia'), ('navarra', 'Navarra'), ('pais_vasco', 'País Vasco'), ('rioja', 'La Rioja'), ('ceuta', 'Ceuta'), ('melilla', 'Melilla')], max_length=30)),
                ('operacion_compra', models.CharField(blank=True, choices=[('itp', 'ITP · compra a particular o segunda transmisión'), ('iva', 'IVA + AJD · primera entrega de promotor')], default='itp', max_length=10)),
                ('supuesto_reducido', models.CharField(blank=True, max_length=40)),
                ('otros_gastos', models.DecimalField(decimal_places=2, default=0, help_text='Notaría, registro, gestoría, tasa de autorización…', max_digits=12)),
                ('precio_participacion', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
                ('participaciones', models.PositiveIntegerField(default=5000)),
                ('tasa_juego_porcentaje', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('comision_pago_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('2.30'), max_digits=5)),
                ('minimo_participaciones', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_venta_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('meses_venta', models.PositiveIntegerField(default=6)),
                ('meses_rifa', models.PositiveIntegerField(default=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, help_text='Opcional: precarga los datos de un proyecto existente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_rifa', to='core.proyecto')),
                ('sorteo', models.OneToOneField(blank=True, help_text='Sorteo en el que se convirtió, si llegó a hacerse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudio_origen', to='sorteo.sorteo')),
            ],
            options={
                'verbose_name': 'estudio de rifa',
                'verbose_name_plural': 'estudios de rifa',
                'ordering': ['-actualizado_en'],
            },
        ),
    ]
