# Generated by Django 4.2.30 on 2026-08-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0009_estudiorifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiorifa',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Un estudio descartado no se borra: se archiva, porque saber qué se probó y por qué no salió vale para el siguiente.'),
        ),
    ]
