# Generated by Django 4.2.30 on 2026-08-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0010_estudiorifa_archivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiorifa',
            name='gastos_asesoria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: se estiman 800 €.', max_digits=10, null=True, verbose_name='Asesoría jurídica y fiscal (€)'),
        ),
        migrations.AddField(
            model_name='estudiorifa',
            name='gastos_gestoria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: se estiman 400 €.', max_digits=12, null=True, verbose_name='Gestoría de la compra (€)'),
        ),
        migrations.AddField(
            model_name='estudiorifa',
            name='gastos_notaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: se calcula por el arancel del RD 1426/1989.', max_digits=12, null=True, verbose_name='Notaría de la compra (€)'),
        ),
        migrations.AddField(
            model_name='estudiorifa',
            name='gastos_notaria_sorteo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: se estiman 400 €.', max_digits=10, null=True, verbose_name='Notaría del sorteo (€)'),
        ),
        migrations.AddField(
            model_name='estudiorifa',
            name='gastos_registro',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: se calcula por el arancel del RD 1427/1989.', max_digits=12, null=True, verbose_name='Registro de la propiedad (€)'),
        ),
        migrations.AddField(
            model_name='estudiorifa',
            name='presupuesto_marketing',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Campaña, creatividades, anuncios. Es lo que separa vender 300 papeletas de vender 3.000.', max_digits=12, verbose_name='Presupuesto de marketing (€)'),
        ),
        migrations.AddField(
            model_name='estudiorifa',
            name='tasa_dgoj',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vacío: 100 €, que es la tasa vigente.', max_digits=10, null=True, verbose_name='Tasa de autorización DGOJ (€)'),
        ),
        migrations.AlterField(
            model_name='estudiorifa',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Descarta el estudio conservándolo. Para deshacerse de él del todo está el borrado.'),
        ),
        migrations.AlterField(
            model_name='estudiorifa',
            name='otros_gastos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que no encaje en los anteriores.', max_digits=12, verbose_name='Otros gastos (€)'),
        ),
    ]
