# Generated by Django 4.2.30 on 2026-08-11 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0011_estudiorifa_gastos_asesoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReenvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reenvio', to='sorteo.sorteo')),
            ],
            options={
                'verbose_name': 'solicitud de reenvío',
                'verbose_name_plural': 'solicitudes de reenvío',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['sorteo', 'creado_en'], name='sorteo_soli_sorteo__f40fad_idx')],
            },
        ),
    ]
