# Generated by Django 4.2.27 on 2026-01-06 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
                ('version_simulador', models.CharField(default='v1', max_length=20)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.estudio')),
            ],
        ),
    ]
