# Generated by Django 4.2.27 on 2025-12-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='fecha',
            new_name='creada',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='beneficio_inversure',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='beneficio_neto_inversure',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='beneficio_participes',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='colchon_seguridad',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='cumple_roi',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='meses',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='precio_breakeven',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='rentabilidad_anualizada',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='rentabilidad_total',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='operacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='operacion',
            name='rentabilidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='beneficio_bruto',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='inversion_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precio_compra',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precio_venta',
            field=models.FloatField(default=0),
        ),
    ]
