# Generated by Django 4.2.27 on 2025-12-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_proyecto_comunidad_proyecto_ibi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('F', 'Persona física'), ('J', 'Persona jurídica')], default='F', max_length=1)),
                ('nombre', models.CharField(help_text='Nombre completo o razón social', max_length=255)),
                ('dni_cif', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('iban', models.CharField(blank=True, help_text='IBAN del cliente (opcional)', max_length=34, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
