# Generated by Django 4.2.27 on 2025-12-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('estudio', 'En estudio'), ('viable', 'Viable'), ('descartado', 'Descartado'), ('operacion', 'En operación')], default='estudio', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='media_valoraciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='val_casafari',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='val_fotocasa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='val_idealista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='val_registradores',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='val_tasacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
