# Generated by Django 4.2.27 on 2026-01-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estudio_bloqueado_estudio_bloqueado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Datos extensibles del proyecto (checklists, notas, hitos, comité final, etc.)', null=True),
        ),
        migrations.CreateModel(
            name='ProyectoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fuente', models.CharField(choices=[('conversion', 'Conversión desde estudio'), ('guardado', 'Guardado de proyecto'), ('cierre', 'Cierre / venta')], default='guardado', help_text='Motivo/origen del snapshot', max_length=20)),
                ('version_num', models.PositiveIntegerField(blank=True, help_text='Número de versión incremental por proyecto (v1, v2, ...)', null=True)),
                ('codigo_version', models.CharField(blank=True, help_text='Código legible (ej: PRJ-2026-000001-v3)', max_length=40)),
                ('nota', models.CharField(blank=True, help_text='Nota corta de la versión (opcional)', max_length=255)),
                ('datos', models.JSONField(help_text='Datos completos congelados del proyecto en este momento (overlay: base_snapshot + reales + kpis)')),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece este snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.proyecto')),
            ],
            options={
                'ordering': ['-creado_en', '-id'],
            },
        ),
    ]
