# Generated by Django 4.2.27 on 2025-12-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_proyecto_estado_proyecto_media_valoraciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='gestion_administracion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='gestion_comercial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
