# Generated by Django 4.2.27 on 2025-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proyecto_gestion_administracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='meses',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada de la operación en meses', null=True),
        ),
    ]
