# Generated by Django 4.2.27 on 2026-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_proyecto_extra_proyectosnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='datos',
            field=models.JSONField(blank=True, default=dict, help_text='Payload JSON del estudio (estado del simulador). Se inicializa vacío para evitar errores en creación.'),
        ),
    ]
