# Generated by Django 4.2.27 on 2026-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingresoproyecto',
            name='tipo',
            field=models.CharField(choices=[('senal', 'Señal / Arras'), ('venta', 'Venta'), ('anticipo', 'Anticipo'), ('devolucion', 'Devolución'), ('indemnizacion', 'Indemnización'), ('otro', 'Otro ingreso')], max_length=20),
        ),
    ]
