# Generated by Django 4.2.27 on 2026-01-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_documentoproyecto_tipo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproyecto',
            name='categoria',
            field=models.CharField(choices=[('inmueble', 'Documentación inmueble'), ('facturas', 'Facturas'), ('fotografias', 'Fotografías'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
    ]
