# Generated by Django 4.2.27 on 2025-12-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_proyecto_lat_proyecto_lon_simulacion_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='Indica si el proyecto ha sido aprobado por el comité'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora de aprobación del proyecto', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='pdf_aprobado',
            field=models.FileField(blank=True, help_text='PDF oficial aprobado del proyecto', null=True, upload_to='proyectos_aprobados/'),
        ),
    ]
