# Generated by Django 4.2.27 on 2026-01-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_documentoproyecto_categoria'),
        ('core', '0017_documentoproyecto_principal'),
    ]

    operations = [
    ]
