# Generated by Django 4.2.27 on 2025-12-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_proyecto_aprobado_proyecto_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(choices=[('adquisicion', 'Adquisición'), ('reforma', 'Reforma'), ('seguridad', 'Seguridad'), ('operativos', 'Gastos operativos'), ('financieros', 'Financieros'), ('legales', 'Legales'), ('venta', 'Venta'), ('otros', 'Otros')], max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('proveedor', models.CharField(blank=True, max_length=255, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imputable_inversores', models.BooleanField(default=True, help_text='Indica si el gasto se imputa a los inversores')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('provisionado', 'Provisionado'), ('anulado', 'Anulado')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='core.proyecto')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacturaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='facturas_proyectos/%Y/%m/')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='core.gastoproyecto')),
            ],
        ),
    ]
