# Generated by Django 4.2.27 on 2025-12-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_gastoproyecto_facturagasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='capital_objetivo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capital total que se desea captar para el proyecto', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='inversion_completa',
            field=models.BooleanField(default=False, help_text='Indica si la inversión del proyecto está completamente cubierta'),
        ),
    ]
