# Generated by Django 4.2.27 on 2025-12-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_proyecto_capital_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_compra',
            field=models.DateField(blank=True, help_text='Fecha real de adquisición del inmueble', null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='impuesto_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de impuesto aplicado', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='impuesto_tipo',
            field=models.CharField(blank=True, help_text='Tipo de impuesto aplicado (ITP / IVA)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_adquisicion',
            field=models.CharField(blank=True, choices=[('directa', 'Compra directa'), ('deuda', 'Compra de deuda'), ('subasta', 'Subasta'), ('dacion', 'Dación en pago')], help_text='Tipo de adquisición del inmueble', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('estudio', 'En estudio'), ('reservado', 'Reservado'), ('comprado', 'Comprado'), ('operacion', 'En operación'), ('vendido', 'Vendido'), ('descartado', 'Descartado')], default='estudio', max_length=20),
        ),
    ]
