# Generated by Django 4.2.27 on 2025-12-31 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_proyecto_fecha_compra_proyecto_impuesto_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('senal', 'Señal / Arras'), ('venta', 'Venta'), ('anticipo', 'Anticipo'), ('devolucion', 'Devolución'), ('otro', 'Otro ingreso')], max_length=20)),
                ('concepto', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Importe del ingreso (positivo o negativo)', max_digits=12)),
                ('imputable_inversores', models.BooleanField(default=True, help_text='Indica si el ingreso computa para inversores')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='core.proyecto')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
