# Generated by Django 4.2.27 on 2025-12-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ingresoproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('escritura', 'Escritura'), ('nota_simple', 'Nota simple'), ('contrato', 'Contrato'), ('tasacion', 'Tasación'), ('otros', 'Otros')], max_length=30)),
                ('archivo', models.FileField(upload_to='proyectos_documentos/%Y/%m/')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.proyecto')),
            ],
        ),
    ]
