# Generated by Django 4.2.27 on 2026-01-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_datoseconomicosproyecto_porcentaje_administracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoproyecto',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Indica si el gasto es real y confirmado (no estimado)'),
        ),
        migrations.AddField(
            model_name='gastoproyecto',
            name='fecha_confirmacion',
            field=models.DateField(blank=True, help_text='Fecha en la que el gasto se considera confirmado', null=True),
        ),
    ]
