# Generated by Django 4.2.27 on 2026-01-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_gastoproyecto_confirmado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoproyecto',
            name='confirmado',
        ),
        migrations.RemoveField(
            model_name='gastoproyecto',
            name='fecha_confirmacion',
        ),
        migrations.AlterField(
            model_name='gastoproyecto',
            name='estado',
            field=models.CharField(choices=[('estimado', 'Estimado'), ('confirmado', 'Confirmado')], default='estimado', max_length=15),
        ),
    ]
