# Generated by Django 4.2.27 on 2026-01-02 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_gastoproyecto_confirmado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosProyectoEstimacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_escritura', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_precio_escritura', models.CharField(default='estimado', max_length=10)),
                ('impuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_impuestos', models.CharField(default='estimado', max_length=10)),
                ('notaria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_notaria', models.CharField(default='estimado', max_length=10)),
                ('registro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_registro', models.CharField(default='estimado', max_length=10)),
                ('gestoria', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_gestoria', models.CharField(default='estimado', max_length=10)),
                ('ibi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_ibi', models.CharField(default='estimado', max_length=10)),
                ('comunidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_comunidad', models.CharField(default='estimado', max_length=10)),
                ('luz', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_luz', models.CharField(default='estimado', max_length=10)),
                ('agua', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_agua', models.CharField(default='estimado', max_length=10)),
                ('alarma', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_alarma', models.CharField(default='estimado', max_length=10)),
                ('cerrajero', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_cerrajero', models.CharField(default='estimado', max_length=10)),
                ('limpieza_vaciado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_limpieza_vaciado', models.CharField(default='estimado', max_length=10)),
                ('obra_reforma', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_obra_reforma', models.CharField(default='estimado', max_length=10)),
                ('obra_materiales', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_obra_materiales', models.CharField(default='estimado', max_length=10)),
                ('obra_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_obra_mano_obra', models.CharField(default='estimado', max_length=10)),
                ('obra_tecnico', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_obra_tecnico', models.CharField(default='estimado', max_length=10)),
                ('obra_licencias', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_obra_licencias', models.CharField(default='estimado', max_length=10)),
                ('obra_contingencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_obra_contingencia', models.CharField(default='estimado', max_length=10)),
                ('comercializacion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_comercializacion', models.CharField(default='estimado', max_length=10)),
                ('administracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_administracion', models.CharField(default='estimado', max_length=10)),
                ('comision_inversure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_comision_inversure', models.CharField(default='estimado', max_length=10)),
                ('valor_transmision_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_estimacion', to='core.proyecto')),
            ],
        ),
    ]
