# Generated by Django 4.2.27 on 2026-01-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_proyecto_acceso_comercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='beneficio_estimado_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Beneficio estimado base heredado del estudio', max_digits=12, null=True),
        ),
    ]
