# Generated by Django 4.2.27 on 2026-01-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_solicitudparticipacion_decision_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoproyecto',
            name='categoria',
            field=models.CharField(choices=[('inmueble', 'Documentación inmueble'), ('facturas', 'Facturas'), ('fotografias', 'Fotografías'), ('presentacion', 'Presentación'), ('otros', 'Otros')], default='otros', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentoproyecto',
            name='tipo',
            field=models.CharField(choices=[('inmueble', 'Documentación inmueble'), ('facturas', 'Facturas'), ('fotografias', 'Fotografías'), ('presentacion', 'Presentación'), ('otros', 'Otros')], default='otros', max_length=30),
        ),
    ]
