# Generated by Django 4.2.27 on 2026-01-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_proyecto_difusion_clientes'),
        ('core', '0032_remove_proyecto_beneficio_estimado_base'),
    ]

    operations = [
    ]
