# Generated by Codex on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_merge_20260120_2109"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentoproyecto",
            name="fecha_factura",
            field=models.DateField(
                blank=True,
                help_text="Fecha de la factura (solo para categoria facturas)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentoproyecto",
            name="importe_factura",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Importe de la factura (solo para categoria facturas)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
