# Generated by Django 5.2.17 on 2026-08-12 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_documentoproyecto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoPinPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('acertado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_pin', to='core.inversorperfil')),
            ],
            options={
                'verbose_name': 'intento de PIN del portal',
                'verbose_name_plural': 'intentos de PIN del portal',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['perfil', 'ip', 'creado'], name='core_intent_perfil__9727f3_idx')],
            },
        ),
    ]
