# Generated by Django 5.2.17 on 2026-08-12 15:29

import core.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_intentopinportal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=core.fields.EncryptedCharField(blank=True, help_text='Soltero/a, casado/a… Aparece en el contrato de préstamo.', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profesion',
            field=core.fields.EncryptedCharField(blank=True, help_text='Profesión u ocupación. Aparece en el contrato de préstamo.', null=True),
        ),
        migrations.AddField(
            model_name='participacion',
            name='contrato_fecha',
            field=models.DateField(blank=True, help_text='Fecha de firma. Si se deja vacía se usa la de la aportación.', null=True),
        ),
        migrations.AddField(
            model_name='participacion',
            name='contrato_interes_bimensual',
            field=models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Interés por período de dos meses, en %. Un 5 % bimensual son seis períodos al año.', max_digits=5),
        ),
        migrations.AddField(
            model_name='participacion',
            name='contrato_meses',
            field=models.PositiveIntegerField(default=12, help_text='Duración del préstamo en meses.'),
        ),
    ]
