# Generated by Django 5.2.17 on 2026-08-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_cliente_estado_civil_cliente_profesion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('cuenta_participe', 'Cuenta en participación')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de firma'), ('firmado', 'Firmado'), ('anulado', 'Anulado')], default='pendiente', max_length=12)),
                ('hash_documento', models.CharField(blank=True, help_text='SHA-256 del PDF del contrato, sin la hoja de evidencias.', max_length=64)),
                ('documento', models.FileField(blank=True, help_text='El PDF firmado, con su hoja de evidencias.', null=True, upload_to='contratos/firmados/')),
                ('nombre_declarado', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('codigo_hash', models.CharField(blank=True, max_length=128)),
                ('codigo_enviado_en', models.DateTimeField(blank=True, null=True)),
                ('codigo_intentos', models.PositiveIntegerField(default=0)),
                ('autorizaciones', models.JSONField(blank=True, default=dict, help_text='Las casillas voluntarias del anexo de protección de datos, tal y como se marcaron.')),
                ('firmado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('participacion', models.ForeignKey(help_text='Protegida: un contrato firmado no puede desaparecer porque se borre la participación.', on_delete=django.db.models.deletion.PROTECT, related_name='firmas', to='core.participacion')),
            ],
            options={
                'verbose_name': 'firma de contrato',
                'verbose_name_plural': 'firmas de contrato',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['participacion', 'estado'], name='core_firmac_partici_8f1682_idx')],
            },
        ),
    ]
