# Generated by Django 5.2.17 on 2026-08-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_firmacontrato_enviado_en_firmacontrato_enviado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacion',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha del acuerdo de resolución. Con ella la participación deja de contar.', null=True),
        ),
        migrations.AddField(
            model_name='participacion',
            name='importe_devuelto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lo que se le devuelve al salir: aportación más lo devengado hasta la fecha.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='participacion',
            name='motivo_baja',
            field=models.CharField(blank=True, help_text='Por ejemplo: cesión de su posición a otro inversor.', max_length=200),
        ),
    ]
