# Generated by Django 4.2.27 on 2026-01-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_fix_noticia_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hero',
            name='fondo_color',
            field=models.CharField(blank=True, help_text='Color de fondo en formato HEX. Ej: #0b1324', max_length=20),
        ),
        migrations.AddField(
            model_name='hero',
            name='fondo_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='landing/hero/fondos/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='meta_1_texto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hero',
            name='meta_1_valor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hero',
            name='meta_2_texto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hero',
            name='meta_2_valor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hero',
            name='meta_3_texto',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='hero',
            name='meta_3_valor',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='hero',
            name='panel_footer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='hero',
            name='panel_texto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hero',
            name='panel_titulo',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
