# Generated by Django 4.2.27 on 2026-01-14 11:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_tag', models.CharField(blank=True, max_length=120)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=320)),
                ('hero_cta_text', models.CharField(blank=True, max_length=80)),
                ('hero_cta_url', models.CharField(blank=True, max_length=200)),
                ('hero_bg_color', models.CharField(blank=True, max_length=20)),
                ('hero_panel_title', models.CharField(blank=True, max_length=120)),
                ('hero_panel_text', models.CharField(blank=True, max_length=200)),
                ('hero_panel_footer', models.CharField(blank=True, max_length=120)),
                ('meta_1_value', models.CharField(blank=True, max_length=40)),
                ('meta_1_label', models.CharField(blank=True, max_length=80)),
                ('meta_2_value', models.CharField(blank=True, max_length=40)),
                ('meta_2_label', models.CharField(blank=True, max_length=80)),
                ('meta_3_value', models.CharField(blank=True, max_length=40)),
                ('meta_3_label', models.CharField(blank=True, max_length=80)),
                ('sections', wagtail.fields.StreamField([('seccion', wagtail.blocks.StructBlock([('icono', wagtail.blocks.CharBlock(max_length=60, required=False)), ('titulo', wagtail.blocks.CharBlock(max_length=120, required=True)), ('texto', wagtail.blocks.TextBlock(required=False))]))], blank=True, use_json_field=True)),
                ('hero_bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_panel_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
