# Generated by Codex on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="solucion_title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="solucion_subtitle",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_text_2",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_stat_1_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_stat_1_value",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_stat_2_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_stat_2_value",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_stat_3_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="quienes_stat_3_value",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_feature_1",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_feature_2",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_feature_3",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_stat_1_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_stat_1_value",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_stat_2_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_stat_2_value",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_stat_3_label",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="homepage",
            name="trans_stat_3_value",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="homepage",
            name="noticias_title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="homepage",
            name="noticias_subtitle",
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
