# Generated by Codex on 2026-01-15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_homepage_content_fields"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                (
                    "projects",
                    wagtail.fields.StreamField(
                        [
                            (
                                "proyecto",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("titulo", wagtail.blocks.CharBlock(max_length=140, required=True)),
                                        ("ubicacion", wagtail.blocks.CharBlock(max_length=140, required=False)),
                                        ("estado", wagtail.blocks.CharBlock(max_length=80, required=False)),
                                        ("anio", wagtail.blocks.CharBlock(max_length=10, required=False)),
                                        ("descripcion", wagtail.blocks.TextBlock(required=False)),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                ("historia", models.TextField(blank=True)),
                ("equipo", models.TextField(blank=True)),
                ("valores", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
