# Generated by Django 4.2.27 on 2026-01-16 10:41

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_projects_and_about_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspage',
            name='projects',
            field=wagtail.fields.StreamField([('proyecto', wagtail.blocks.StructBlock([('imagen', wagtail.images.blocks.ImageChooserBlock(required=False)), ('titulo', wagtail.blocks.CharBlock(max_length=140, required=True)), ('ubicacion', wagtail.blocks.CharBlock(max_length=140, required=False)), ('estado', wagtail.blocks.CharBlock(max_length=80, required=False)), ('anio', wagtail.blocks.CharBlock(max_length=10, required=False)), ('descripcion', wagtail.blocks.TextBlock(required=False))]))], blank=True, use_json_field=True),
        ),
    ]
