# Generated by Django 4.2.27 on 2026-04-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccess_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='role',
            field=models.CharField(blank=True, choices=[('administracion', 'Administracion'), ('direccion', 'Direccion'), ('comercial', 'Comercial'), ('marketing', 'Marketing'), ('moderators', 'Moderators')], default='', help_text='Rol principal del usuario', max_length=20),
        ),
    ]
